Feat/additional paths
swayprotocol/creator-pools-api pull request #18
Opened 2022-05-30 13:25 UTC by mayki0909

https://app.clickup.com/t/2e5ww7u

2022-05-31 06:41 UTC, matjaz-NFT requested changes

2022-05-31 06:41 UTC, matjaz-NFT commented on src/stake/stake.service.ts
> +    averageAPY = averageAPY / stakes.length
can happen that stakes length is 0?

2022-05-31 06:41 UTC, matjaz-NFT commented on src/stake/stake.service.ts
> +    const pool = await this.poolService.findOneByHandle(poolName)
what if pool is not found/doesn't exist anymore?

2022-05-31 06:41 UTC, matjaz-NFT commented on src/stake/stake.service.ts
> +      social: poolName.split('-')[0],
poolName is input of function, which is not safe to use. here you could use pool object to get pool name instead?

2022-05-31 06:41 UTC, matjaz-NFT commented on src/stake/stake.service.ts
> +        if (distribution[chanel]) distribution[chanel] += stake.amount
you could use if case to set distribution[chanel] to 0 first time, then you can always run `distribution[chanel] += stake.amount` after

2022-05-31 06:41 UTC, matjaz-NFT commented on src/stake/stake.service.ts
> +      distributionArray.push({chanel, distribution: (distribution[chanel]/totalStaked). toFixed(3)})
possible division with 0?

2022-05-31 07:44 UTC, mayki0909 commented on src/stake/stake.service.ts
> +    averageAPY = averageAPY / stakes.length
Yes it can, but it doesn't crash app
![image](https://user-images.githubusercontent.com/50374602/171119903-f4341c43-ddbf-443c-8d98-84778c989dff.png)

2022-05-31 07:52 UTC, mayki0909 commented on src/stake/stake.service.ts
> +    const pool = await this.poolService.findOneByHandle(poolName)
It returns null response as shown on screenshot above

2022-05-31 07:53 UTC, mayki0909 commented on src/stake/stake.service.ts
> +      social: poolName.split('-')[0],
Okey

2022-05-31 10:56 UTC, matjaz-NFT approved these changes

2022-05-31 10:56 UTC, matjaz-NFT commented on src/stake/stake.service.ts
> +    averageAPY = averageAPY / stakes.length
shouln't we return non 200 response, if pool is not found?

2022-05-31 12:15 UTC, mrVers commented on src/stake/stake.service.ts
> +        const chanel = poolSplit[0]
Typo. `chanel` -> `channel`

2022-06-01 09:12 UTC, mayki0909 commented on src/stake/stake.service.ts
> +    averageAPY = averageAPY / stakes.length
Now it return 400 not found

2022-06-01 11:30 UTC, mrVers approved these changes

2022-06-01 12:54 UTC, merged